Haripriya/ecom/ecom/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ecomapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Haripriya/ecom/ecomapp/urls.py
from . import views
from django.urls import path
app_name='ecomapp'
urlpatterns = [
    path('', views.allProdCat, name='allProdCat'),
    path('<slug:c_slug>/', views.allProdCat, name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/', views.proDetail, name='ProdCatDetail')
]

Haripriya/ecom/ecomapp/models.py
from django.db import models

# Create your models here.
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='category', blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_url(self):
        return reverse("ecomapp:products_by_category", args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)


class Product(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product', blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def get_url(self):
        return reverse("ecomapp:ProdCatDetail", args=[self.category.slug, self.slug])

    def __str__(self):
        return '{}'.format(self.name)

Haripriya/ecom/ecomapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from.models import Category,Product
from django.core.paginator import Paginator,EmptyPage,InvalidPage
# Create your views here.
def allProdCat(request,c_slug=None):
    c_page=None
    products_list=None
    if c_slug!=None:
        c_page=get_object_or_404(Category, slug=c_slug)
        products_list=Product.objects.all().filter(category=c_page, available=True)
    else:
        products_list = Product.objects.all().filter(available=True)
    paginator = Paginator(products_list, 6)
    try:
        page = int(request.GET.get('page', '1'))
    except:
        page = 1
    try:
        products = paginator.page(page)
    except (EmptyPage, InvalidPage):
        products = paginator.page(paginator.num_pages)

    return render(request,'category.html',{'category':c_page,'products':products})

def proDetail(request,c_slug,product_slug):
    try:
        product=Product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e
    return render(request,'product.html',{'product':product})

Haripriya/ecom/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/custom.css'%}">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100&display=swap" rel="stylesheet">
<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <title>{% block title %}{% endblock %}</title>
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
</head>
<body>
<div class="container">
    {% include 'header.html' %}
    {% include 'nav.html' %}
    {% block content %}
    {% endblock %}
</div>
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

</body>
</html>

Haripriya/ecom/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
     {% if category %}
         {{category.description| truncatewords:155}}
     {% else %}
         Welcome to the cart store where you can buy awesome items
     {% endif %}
{% endblock %}

{% block title %}
    {% if category %}
          {{category.name}}-shop cart
    {% else %}
          www.Restro.com
    {% endif %}
{% endblock %}
{% block content %}
     {% if category %}
           <div class="row my_row_class">
               <div class="mx-auto">
                   <p><a href="{% url 'ecomapp:allProdCat' %}">Home| </a>{{category.name}}</p>
               </div>
           </div>
     {% endif %}
   <div class="mx-auto">
       {% if category %}
             <img class="my_image" src="{{category.image.url}}" alt="{{category.name}}">
   </div>
     <br>
     <div>
         <h1 class="text-center my_title">{{category.name}}</h1>
         <p   class="text-justify">{{category.description}}</p>

     </div>
     {% else %}
         <div>
          <center><img class="my_image my_image_padding" src="{% static 'img/banner.jpg' %}" style="width:1310px;"></center>
         </div>
        <br>
       <div>
           <h1 class="text-center my_title">Our Products Collections</h1>
           <p class="text-justify">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley</p>
       </div>
     {% endif %}
      <div class="container">
          <div class="row max-auto">
               {% for product in products.object_list %}
                <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
                  <div class="card text-center" style="min-width:18rem;">
                      <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}" style="width:285px;height:350px;color:black;" > </a>
                  <div class="card-body">
                      <h4>{{product.name}}</h4>
                      <p>${{product.price}}</p>
                  </div>
                  </div>
              </div>
              {% endfor %}
          </div>
          <div class="mx-auto">
              <div class="text-center">
              {% for pg in products.paginator.page_range %}
              <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} activate {% endif %}">{{pg}}</a>
              {% endfor %}
              </div>
          </div>
      </div>
{% endblock %}


<!--style="width:250px;height:350px;color:black;"-->
<!---->

Haripriya/ecom/templates/header.html
{% load static %}
<header>
<div>
    <center>
      <a href="{% url 'ecomapp:allProdCat' %}"></a>  <img src ="{% static 'img/logo123.png' %}"  alt="this is the logo of online shop site" style="width:200px;height:200px;">
    </center>
</div>
</header>

Haripriya/ecom/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">

          <a class="nav-link" href="{% url 'ecomapp:allProdCat' %}">Home</a>
        </li>
        <li class="nav-item dropdown {% if 'ecomapp' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Shop
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'ecomapp:allProdCat' %}">All Products</a></li>
              {% for cat in links %}
            <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>

            {% endfor %}
          </ul>
        </li>
         {% if item_count > 0 %}
        <li class="nav-item">

          <a class="nav-link" href="#">Your Cart<i class="fas fa-shopping-cart">{{item_count}}</i></a>

        </li>
         {% endif %}
      </ul>
      <form class="d-flex" action="#" method="get">
        {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search"  name="q" aria-label="Search">
        <button class="btn btn-outline-success" type="submit"><i class="fas fa-search"></i></button>
      </form>
    </div>
  </div>
</nav>



<!---->

Haripriya/ecom/templates/product.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
{{product.description | truncatewords:155 }}
{% endblock %}

{% block title %}
      {{product.name}}-Shop Cart
{% endblock %}

{% block content %}

   <div class="row my_prod_row_class">
         <div class="mx_auto">
              <p><a href="{% url 'ecomapp:allProdCat' %}">Home</a> | <a href="{{product.category.get_url}}">{{product.category}}</a>|{{product.name}}</p>
         </div>
       <div class="container">
           <br>

           <div class="row">
               <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                   <div style="min-width:18rem">
                       <img src="{{product.image.url}}" alt="{{product.name}}" width="300px" height="350px">
                   </div>
               </div>

                   <div class="col-12 col-sm-12 col-md-12 col-lg-6">
                       <div>
                       <h1 class="my_prod_title">{{product.name}}</h1>
                       <p>${{product.price}}</p>
                       <p class="my_title">Product Description</p>
                       <p class="text-justify my_prod_text">{{product.description}}</p>
                       {% if product.stock <= 0 %}
                       <p class="text-justify my_prod_text"><b>Out of stock</b></p>
                       {% else %}
                       <a class="btn btn-secondary" href="#">Add to Cart</a>
                       {% endif %}
                   </div>
               </div>
           </div>
       </div></div>
{% endblock %}